print("Hello world, my name is Giorgi")
print("I am 15 years old")
print("I recently got interested in programming")
print("I like reading and studying history")
print("I really liked my first lesson in GOA")
print("I have a great mentor that give great lessons")
print("I want to do some exercises")
print("why did it have to be 40, this is going very slowly")
print("but it's okay I'll still do it")
print("Chads never give up")
print("I have to write an essay for Georgian and I'm kind of lazy but it's also kind of interesting")
print("I have math class tomorrow")
print("I also have GOA lesson tomorrow from 13:00 to 15:00")
print("I don't have to go to school on monday ;))")
print("This is only the 15th?")
print("it's okay every print is a step closer to 40 ;))")
print("now 17th!!")
print("Did you know that ancient egyptians believed that every pharaoh was a reincarnation of the god Horus?")
print("Althought the mesopotamians had a similar belief system to egyptians, the differed in many aspects")
print("I don't know what I'm writing anymore")
print("For example egyptians believed that everything came from an ocean that went on forever, they called it 'Nun;? I think so")
print("and in the ocean the god atum created himself")
print("The sky and the ground were one at first, before air separated them")
print("because religious priests had too much political power, one pharaoh by the name on Amenhotep, banned polytheism")
print("I live in Zugdidi")
print("getting closer to 40")
print("I also have to create a giant castle lol")
print("I have little to no drawing skills so this will be interesting")
print("getting closer and closer to 40")
print("already 30!!!!")
print("Hello world again!!")
print("linking two string elements toghether is called concatenation")
print("I am now writing string elements")
print("I really don't know what to write anymore")
print("I am literally Napoleon")
print("No I am not")
print("three remaining to 40")
print("I am tired")
print("closer")
print("Goodbye World!!!")
