x = int(input('Enter x: '))
y = input('Enter y: ')
z = int(input('Enter z: '))
f = input('Enter f: ')
print(x * int(y))
print(x // z)
print(x * int(f))
print(x + z)
print(int(y) - int(f))
print(z // int(f))
print(x * z)
print(x - z)
print(int(str(x)) + int(f))
print(int(f) - z)

